-- update_schema_v4.sql
-- Script to update the database schema for version 4 functionalities.

-- IMPORTANT: Backup your database before applying these changes.

-- --------------------------------------------------------
--
-- Table structure for table `admins`
--
CREATE TABLE IF NOT EXISTS `admins` ( -- Added IF NOT EXISTS for robustness
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Example for adding a first admin user (run manually or via a separate script):
-- INSERT INTO `admins` (`username`, `password_hash`) VALUES
-- ('admin', '$2y$10$YOUR_PASSWORD_HASH_HERE');
-- Replace YOUR_PASSWORD_HASH_HERE with a real hash generated by:
-- php -r "echo password_hash('your_secure_password', PASSWORD_DEFAULT) . PHP_EOL;"

-- --------------------------------------------------------
--
-- Altering table `matches` to add `cover_image_filename`
--
ALTER TABLE `matches`
ADD COLUMN `cover_image_filename` VARCHAR(255) DEFAULT NULL COMMENT 'Filename of the uploaded cover image for the match' AFTER `league_id`;

-- --------------------------------------------------------
--
-- Instructions for new directory creation (to be done manually on the server):
--
-- For the match cover image upload functionality to work, you will need to create
-- the following directory in your project's `uploads/` path,
-- and ensure it is writable by your web server:
--
--   uploads/covers/matches/
--
-- Example permissions (if using Linux and 'uploads' directory already exists):
-- mkdir -p uploads/covers/matches
-- chmod -R 755 uploads  (ensure parent 'uploads' and 'covers' also have appropriate permissions)
-- sudo chown -R www-data:www-data uploads/covers/matches (replace www-data with your web server user/group)
--
-- The exact chmod/chown commands might vary based on your server setup and security policies.
--
